FROM eclipse-temurin:25-jdk

RUN apt-get update && apt-get install -y \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN mkdir -p /root/.gradle

CMD ["./gradlew", "bootRun"]
